### ISSUE TITLE
Application Groups?

### ISSUE THREAD

**Issue by jantman** [demandmedia/ice_pick#1]
We've just started using Ice, and we're using the Application Groups feature, with the built-in basic Resource Service / tag-to-Resource Group functionality (i.e. ``ice.customTags=tag1,tag2``).

I've been working on some python code using requests to automate creation of Application Groups - i.e. getting the current Resource Groups, products, Application Groups, etc. and deleting/creating/updating Application Groups.

At the moment this code lives in an internal tool. Would there be any interest in a pull request to add this functionality to ice_pick? If so, I'd be happy to submit one.

**Comment by dm-mediaops** [comment]
Hi Jason,

Yes, we would absolutely be interested in merging new functionality into
ice_pick.  Please do submit your pull request and we'll review it.

Thanks!
Frank Shotwell


On Sun, Mar 1, 2015 at 5:44 AM, Jason Antman <notifications@github.com>
wrote:

> We've just started using Ice, and we're using the Application Groups
> feature, with the built-in basic Resource Service / tag-to-Resource Group
> functionality (i.e. ice.customTags=tag1,tag2).
>
> I've been working on some python code using requests to automate creation
> of Application Groups - i.e. getting the current Resource Groups, products,
> Application Groups, etc. and deleting/creating/updating Application Groups.
>
> At the moment this code lives in an internal tool. Would there be any
> interest in a pull request to add this functionality to ice_pick? If so,
> I'd be happy to submit one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/demandmedia/ice_pick/issues/1>.
>

-- 
Please NOTE: This electronic message, including any attachments, may 
include privileged, confidential and/or inside information owned by Demand 
Media, Inc. Any distribution or use of this communication by anyone other 
than the intended recipient(s) is strictly prohibited and may be unlawful. 
If you are not the intended recipient, please notify the sender by replying 
to this message and then delete it from your system. Thank you.

**Comment by jantman** [comment]
Just for clarity, I've submitted #2 for this.

**Comment by jantman** [comment]
This was fixed in #2
