### ISSUE TITLE
Can't install due to test requirement conflicts

### ISSUE THREAD

**Issue by jantman** [demandmedia/ice_pick#4]
[setup.py](https://github.com/demandmedia/ice_pick/blob/master/setup.py) uses all of requirements.txt as ``install_requires``. This is improper, and causes a number of issues:

1. nose, mock, coverage, and everything else in [requirements.txt](https://github.com/demandmedia/ice_pick/blob/master/requirements.txt) are all installed when you ``pip install ice_pick``, even though only ``requests`` is an actual runtime dependency; the rest are all test dependencies.
2. This also means that if ice_pick is included as a requirement in another project that already uses coverage, but a different version, that upstream project is impossible to test because of the unnecessary version conflict.

I'll cut a pull request to try and address this.

**Comment by qwcode** [comment]
also, for `install_requires` it's bad practice to used pinned versions for a public project like this.  you don't want to tell the whole world to use  `requests==2.2.1` 

most likely `requests==2.2.1` is the version demandmedia is using internally for repeatability, and requirements files are great for that, but that shouldn't be used as the foundation for `install_requires`.

`install_requires` should contain the minimal requirement needed for you project to work.... maybe `requests>=2`

see https://packaging.python.org/en/latest/requirements.html

**Comment by harph** [comment]
Done. It's up. Version 0.5.

**Comment by jantman** [comment]
Thanks so much!
